--Supprimer les FK si au cas ou elles existent
ALTER TABLE ACTIONS DROP CONSTRAINT FK_ACTIONNAIRE_2;
ALTER TABLE ACTIONS DROP CONSTRAINT FK_ENTREPRISE;
ALTER TABLE OFFRES DROP CONSTRAINT FK_ENTREPRISE_2;
ALTER TABLE OFFRES DROP CONSTRAINT FK_ACTIONNAIRE_OFFRE;
ALTER TABLE OFFRES DROP CONSTRAINT FK_ACTIONNAIRE_OP_IM;
ALTER TABLE PRODUCTEURCONSOMMATEURS DROP CONSTRAINT FK_ENTREPRISE_3;
ALTER TABLE HISTORIQUESACTIONNAIRES DROP CONSTRAINT FK_ACTIONNAIRE_3;
ALTER TABLE HISTORIQUESENTREPRISES DROP CONSTRAINT FK_HISTORIQUE_ENTRE;

--Supprimer les tables si elles existent dans la BD
DROP  TABLE  ACTIONNAIRES;
DROP  TABLE  ACTIONS;
DROP  TABLE  ENTREPRISES;
DROP  TABLE  HISTORIQUESACTIONNAIRES;
DROP  TABLE  HISTORIQUESENTREPRISES;
DROP  TABLE  OFFRES;
DROP  TABLE  PRODUCTEURCONSOMMATEURS;

--Création des tables

CREATE TABLE ACTIONS
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
quantite INTEGER NOT NULL,
FK_ACTIONNAIRE_2 INTEGER NOT NULL,
FK_ENTREPRISE INTEGER NOT NULL
) ;
CREATE TABLE ACTIONNAIRES
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(50) NOT NULL,
CAPITAL DOUBLE NOT NULL
) ;
CREATE TABLE ENTREPRISES
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(50) NOT NULL,
CAPITAL DOUBLE NOT NULL,
CAPITAL_VENTE_TOTAL DOUBLE NOT NULL,
QUANTITE_RES_VENTE_TOTALE INTEGER NOT NULL,
QUANTITE_RESSOURCE INTEGER NOT NULL
) ;
CREATE TABLE OFFRES
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
QUANTITE INTEGER NOT NULL,
PRIX DOUBLE NOT NULL,
STATUT INTEGER NOT NULL,
OPERATIONS INTEGER NOT NULL,
DATE_ECHANGE DATE,
FK_ENTREPRISE_2 INTEGER NOT NULL,
FK_ACTIONNAIRE_OFFRE INTEGER NOT NULL,
FK_ACTIONNAIRE_OP_IM INTEGER

) ;

CREATE TABLE PRODUCTEURCONSOMMATEURS
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STATUT INTEGER NOT NULL,
FIABILITE DOUBLE NOT NULL,
QUANTITE_RESSOURCE INTEGER NOT NULL,
FK_ENTREPRISE_3 INTEGER NOT NULL

) ;

CREATE TABLE HISTORIQUESENTREPRISES
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DATE_HISTO DATE NOT NULL,
QUANTITE_RESSOURCE INTEGER NOT NULL,
CAPITAL_VENTE_TOTAL DOUBLE NOT NULL,
QUANTITE_RES_VENTE_TOTALE INTEGER NOT NULL,
CAPITAL DOUBLE NOT NULL,
FK_HISTORIQUE_ENTRE INTEGER NOT NULL
) ;
CREATE TABLE HISTORIQUESACTIONNAIRES
(
id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CAPITAL DOUBLE NOT NULL,
DATE_HISTO DATE NOT NULL,
FK_ACTIONNAIRE_3 INTEGER NOT NULL
) ;



--Ajout des contraintes FK
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONNAIRE_2
Foreign Key (FK_ACTIONNAIRE_2) REFERENCES ACTIONNAIRES (ID);

ALTER TABLE ACTIONS ADD CONSTRAINT FK_ENTREPRISE
Foreign Key (FK_ENTREPRISE) REFERENCES ENTREPRISES (ID);

ALTER TABLE OFFRES ADD CONSTRAINT FK_ENTREPRISE_2
Foreign Key (FK_ENTREPRISE_2) REFERENCES ENTREPRISES (ID);

ALTER TABLE OFFRES ADD CONSTRAINT FK_ACTIONNAIRE_OFFRE
Foreign Key (FK_ACTIONNAIRE_OFFRE) REFERENCES ACTIONNAIRES (ID);

ALTER TABLE OFFRES ADD CONSTRAINT FK_ACTIONNAIRE_OP_IM
Foreign Key (FK_ACTIONNAIRE_OP_IM) REFERENCES ACTIONNAIRES (ID);

ALTER TABLE PRODUCTEURCONSOMMATEURS ADD CONSTRAINT FK_ENTREPRISE_3
Foreign Key (FK_ENTREPRISE_3) REFERENCES ENTREPRISES (ID);

ALTER TABLE HISTORIQUESACTIONNAIRES ADD CONSTRAINT FK_ACTIONNAIRE_3
Foreign Key (FK_ACTIONNAIRE_3) REFERENCES ACTIONNAIRES (ID);

ALTER TABLE HISTORIQUESENTREPRISES ADD CONSTRAINT FK_HISTORIQUE_ENTRE
Foreign Key (FK_HISTORIQUE_ENTRE) REFERENCES ENTREPRISES (ID);

--Ajout des contraintes d'unicité
ALTER TABLE ACTIONS ADD CONSTRAINT UNIQ_KEY_ACTIONS UNIQUE (FK_ACTIONNAIRE_2, FK_ENTREPRISE)